apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app
  labels:
    name: my-app
    type: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels:
        name: my-app
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 4
